public class MyClass {
  public static void main(String[] args) {
    int myNum = 9;               // integer (whole number)
    float myFloatNum = 9.99f;    // floating point number
    char myLetter = 'A';         // character
    boolean myBool = true;       // boolean
    String myText = "Hello";     // String   
    System.out.println(myNum);
    System.out.println(myFloatNum);
    System.out.println(myLetter);
    System.out.println(myBool);
    System.out.println(myText);
  }
}
